version: "3"

services:
  node-server:
    build: .
    container_name: codedragon_api
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: codedragon_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: codedragon_admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: codedragon

volumes:
  db_data:
